export enum OperationTypesEnum {
  SEARCH_AND_RESCUE = 'SEARCH_AND_RESCUE',
  EMERGENCY_RESCUE = 'EMERGENCY_RESCUE',
  WATER_RESCUE = 'WATER_RESCUE',
  FIRE_AND_RESCUE = 'FIRE_AND_RESCUE',
  MEDICAL_RESCUE = 'MEDICAL_RESCUE',
}
